### ISSUE TITLE
Refactor the batch hash logic by the merkle tree

### ISSUE THREAD

**Issue by cool-develope** [Lagrange-Labs/lagrange-node#413]
## Context

Currently, the batch hash is calculated by appending the hash of the blocks sequentially. It makes difficult to generate the given block proof in not only zkProof but also in the raw proof scheme. Refactor it to the merkle root hash.

**Comment by omarryehia2** [comment]
to attach to Axelar deployment meta-issue

**Comment by mastereng12** [comment]
done!
