### ISSUE TITLE
bug: the client batch storing logic is stuck

### ISSUE THREAD

**Issue by cool-develope** [Lagrange-Labs/lagrange-node#431]
## Context

The bug is reported on the Holesky Arbitrum testnet, the client batch storing process is stuck after long running. The problem is some batches are missed from the rpc channel, as a result the storing batch number is forward than the current batch number.

## Tasks

- [x] Investigate the reason of the batch channel leaks
- [x] #434
- [x] #432
- [x] #435

**Comment by omarryehia2** [comment]
keeping open for new stress tests, closing 06/03 if all checks out
